// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	aggregates "github.com/vinitius/smaug/internal/aggregates"
)

// VWAPPublisher is an autogenerated mock type for the VWAPPublisher type
type VWAPPublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: aggregate
func (_m *VWAPPublisher) Publish(aggregate aggregates.VWAPAggregate) {
	_m.Called(aggregate)
}
