// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	aggregates "github.com/vinitius/smaug/internal/aggregates"

	mock "github.com/stretchr/testify/mock"
)

// VWAPMessageBrokerClient is an autogenerated mock type for the VWAPMessageBrokerClient type
type VWAPMessageBrokerClient struct {
	mock.Mock
}

// Send provides a mock function with given fields: aggregate
func (_m *VWAPMessageBrokerClient) Send(aggregate aggregates.VWAPAggregate) {
	_m.Called(aggregate)
}
